on:
  push:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      api-level: 29
      api-target: default
      api-arch: x86_64
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: gradle
    - name: Cold Boot Android Emulator
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        emulator-boot-timeout: 600
        api-level: ${{ env.api-level }}
        target: ${{ env.api-target }}
        arch: ${{ env.api-arch }}
        avd-name: test_device
        profile: Galaxy Nexus
        cores: 2
        ram-size: 2048M
        sdcard-path-or-size: 100M
        force-avd-creation: false
        emulator-options: -no-snapshot-load -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
        disable-animations: false # Disabling takes little bit of time to exec
        channel: canary
        script: echo "Generated AVD Snapshot."
    - name: Install dependencies
      run: npm i
    - name: Fetch Cached Android Release
      id: cached-app
      uses: actions/cache@v3
      with:
        key: android-app-${{ runner.os }}
        path: |
          android/app/build/outputs/apk/release/app-release.apk
          android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk
    - name: Build Android Release
      if: ${{ steps.cached-app.outputs.cache-hit != 'true' }}
      timeout-minutes: 90
      run: npx detox build --configuration android.att.release
    - name: Quick Boot and Run Android Tests
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        emulator-boot-timeout: 300
        api-level: ${{ env.api-level }}
        target: ${{ env.api-target }}
        arch: ${{ env.api-arch }}
        avd-name: test_device
        profile: Galaxy Nexus
        cores: 2
        ram-size: 2048M
        sdcard-path-or-size: 100M
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        channel: canary
        script: npx detox test --configuration android.att.release --record-videos failing
    - name: Store Artifacts on Fail
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: detox-artifacts
        path: artifacts

