on:
  push:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      api-level: 30
      api-target: google_atd
      api-arch: x86
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: gradle
    # - name: Setup Gradle
    #   uses: gradle/gradle-build-action@v2
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Create AVD
      env:
        api-package: "system-images;android-${{ env.api-level }};${{ env.api-target }};${{ env.api-arch }}"
      run: |
        sudo apt-get install libpulse0:i386
        sdkmanager --install '${{ env.api-package }}' > /dev/null
        echo no | avdmanager create avd -n test_device --package '${{ env.api-package }}'
    # - name: Install dependencies
    #   run: npm i
    # - name: Build Android Release
    #   timeout-minutes: 90
    #   run: npx detox build --configuration android.att.release
    - name: Start Android Emulator
      timeout-minutes: 15
      run: |
        $ANDROID_SDK_ROOT/emulator/emulator -avd test_device -gpu swiftshader_indirect -no-accel -noaudio -no-boot-anim -camera-back none &
        adb wait-for-device shell 'echo "Device started."; while [[ -z $(getprop sys.boot_completed) ]]; do echo "Waiting for boot."; sleep 5; done;'
    # - name: Run Detox Tests
    #   timeout-minutes: 5
    #   run: npx detox test --configuration android.att.release --record-videos failing
    - name: Stop Emulator
      if: always()
      run: adb devices | grep emulator | cut -f1 | while read line; do adb -s $line emu kill; done
    - name: Store Artifacts on Fail
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: detox-artifacts
        path: artifacts

