on:
  push:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      api-level: 29
      api-target: google_apis
      api-arch: x86
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
          ~/.android/debug.keystore
        key: avd-${{ env.api-level }}-${{ matrix.os }}-${{ env.api-target }}
    - name: run emulator to generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: ReactiveCircus/android-emulator-runner@v2.28.0
      with:
        # API level of the platform and system image - e.g. 23 for Android Marshmallow, 29 for Android 10
        api-level: ${{ env.api-level }}
        # target of the system image - default, google_apis, google_apis_playstore, aosp_atd, google_atd, android-wear, android-wear-cn, android-tv or google-tv
        target: ${{ env.api-target }}
        arch: ${{ env.api-arch }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        disable-spellchecker: true
        disable-linux-hw-accel: auto
        working-directory: ./android
        script: echo "Emulator is running!"